### ISSUE TITLE
Doesn't run in a ruby-slim container because of missing libgomp

### ISSUE THREAD

**Issue by mepatterson** [ankane/ngt-ruby#2]
(posting this here to save someone else the hassle of figuring this out)

After building up a docker container on the `ruby:2.7.0-slim` image and gem installing this library, it would error out, complaining about `libgomp.so.1: cannot open shared object file: No such file or directory`. 

The error is pretty self-explanatory. On that particular image (and I'm guessing may be relevant to other linux containers and servers), that particular library needs to be explicitly installed.

In my case, adding this to my Dockerfile solved the issue:

```
RUN apt-get install -y libgomp1
```

**Comment by ankane** [comment]
Thanks for sharing @mepatterson! I'm sure this will help future searchers/readers.

May add this to the readme at a later date - most Linux systems should have it already installed, but this is great for ones that don't. `libgomp1` is OpenMP, which is needed for performance 🔥
